name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1                  
  ECR_REPOSITORY: my_app/my_app           
  ECS_SERVICE: hhh                
  ECS_CLUSTER: testgithub                
  ECS_TASK_DEFINITION: ./task.json 
                                               
  CONTAINER_NAME: test          
                                               
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      -  name: Initialise project and deploy terraform
         run: |
          terraform fmt
          terraform init -input=false
          terraform plan -out=tfplan
          terraform apply tfplan
          
